name: Run TestRunner on Windows

on:
  push:
    branches:
      - '**'  # Trigger on any branch push

jobs:
  test:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run TestRunner
        run: mvn -Dtest=TestRunner test
