# This workflow builds a Java project with Maven and uploads reports and logs

name: Booking  API Cucumber Workflow

on:
  push:
    branches: [ "**" ]
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Test execution
        run: mvn clean test

      - name: Upload execution report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: target/report
      - name: Commit and push test report to repo
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add target/report
          git commit -m "Add test report [CI skip]" || echo "No changes to commit"
          git push origin ${{ github.ref }}
      - name: Upload execution logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: target/logs
