# This workflow builds a Java project with Maven and uploads reports and logs

name: API Cucumber Workflow

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Test execution
        run: mvn clean test

      - name: Upload execution report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: target/report

      - name: Upload execution logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: target/logs
